export const CommunicationTypes = {
    SEND_CART_PRODUCTS: 'SEND_CART_PRODUCTS',
    REMOVED_PRODUCT_FROM_CART: 'REMOVED_PRODUCT_FROM_CART',
    CHANGE_PRODUCT_QUANTITY: 'INCREASE_PRODUCT_QUANTITY'
}