export const CommunicationTypes = {
    SEND_ALL_PRODUCTS: 'SEND_ALL_PRODUCTS',
    SEND_CART_PRODUCTS: 'SEND_CART_PRODUCTS',
    SEND_PRODUCT: 'SEND_PRODUCT',
    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
    REMOVED_PRODUCT_FROM_CART: 'REMOVED_PRODUCT_FROM_CART',
    CHANGE_PRODUCT_QUANTITY: 'INCREASE_PRODUCT_QUANTITY',
    NAVIGATE: 'NAVIGATE'
}